export default [
  {
    "id": 1,
    "name": "Ana",
    "url": "https://overwatch-api.net/api/v1/hero/1",
    "alignImage": "top",
    "role": "Support",
  },
  {
    "id": 2,
    "name": "Bastion",
    "url": "https://overwatch-api.net/api/v1/hero/2",
    "alignImage": "top",
    "role": "Defense",
  },
  {
    "id": 3,
    "name": "D.Va",
    "url": "https://overwatch-api.net/api/v1/hero/3",
    "alignImage": "bottom",
    "role": "Tank",
  },
  {
    "id": 4,
    "name": "Genji",
    "url": "https://overwatch-api.net/api/v1/hero/4",
    "alignImage": "top",
    "role": "Offense",
  },
  {
    "id": 5,
    "name": "Hanzo",
    "url": "https://overwatch-api.net/api/v1/hero/5",
    "alignImage": "top",
    "role": "Defense",
  },
  {
    "id": 6,
    "name": "Junkrat",
    "url": "https://overwatch-api.net/api/v1/hero/6",
    "alignImage": "center",
    "role": "Defense",
  },
  {
    "id": 7,
    "name": "Lúcio",
    "url": "https://overwatch-api.net/api/v1/hero/7",
    "alignImage": "top",
    "role": "Support",
  },
  {
    "id": 8,
    "name": "McCree",
    "url": "https://overwatch-api.net/api/v1/hero/8",
    "alignImage": "top",
    "role": "Offense",
  },
  {
    "id": 9,
    "name": "Mei",
    "url": "https://overwatch-api.net/api/v1/hero/9",
    "alignImage": "top",
    "role": "Defense",
  },
  {
    "id": 10,
    "name": "Mercy",
    "url": "https://overwatch-api.net/api/v1/hero/10",
    "alignImage": "center top",
    "role": "Support",
  },
  {
    "id": 11,
    "name": "Pharah",
    "url": "https://overwatch-api.net/api/v1/hero/11",
    "alignImage": "top",
    "role": "Offense",
  },
  {
    "id": 12,
    "name": "Reaper",
    "url": "https://overwatch-api.net/api/v1/hero/12",
    "alignImage": "top",
    "role": "Offense",
  },
  {
    "id": 13,
    "name": "Reinhardt",
    "url": "https://overwatch-api.net/api/v1/hero/13",
    "alignImage": "top",
    "role": "Tank",
  },
  {
    "id": 14,
    "name": "Roadhog",
    "url": "https://overwatch-api.net/api/v1/hero/14",
    "alignImage": "top",
    "role": "Tank",
  },
  {
    "id": 15,
    "name": "Soldier: 76",
    "url": "https://overwatch-api.net/api/v1/hero/15",
    "alignImage": "top",
    "role": "Offense",
  },
  {
    "id": 16,
    "name": "Symmetra",
    "url": "https://overwatch-api.net/api/v1/hero/16",
    "alignImage": "top",
    "role": "Support",
  },
  {
    "id": 17,
    "name": "Torbjörn",
    "url": "https://overwatch-api.net/api/v1/hero/17",
    "alignImage": "top",
    "role": "Defense",
  },
  {
    "id": 18,
    "name": "Tracer",
    "url": "https://overwatch-api.net/api/v1/hero/18",
    "alignImage": "top",
    "role": "Offense",
  },
  {
    "id": 19,
    "name": "Widowmaker",
    "url": "https://overwatch-api.net/api/v1/hero/19",
    "alignImage": "top",
    "role": "Defense",
  },
  {
    "id": 20,
    "name": "Winston",
    "url": "https://overwatch-api.net/api/v1/hero/20",
    "alignImage": "left top",
    "role": "Tank",
  },
  {
    "id": 21,
    "name": "Zarya",
    "url": "https://overwatch-api.net/api/v1/hero/21",
    "alignImage": "top",
    "role": "Tank",
  },
  {
    "id": 22,
    "name": "Zenyatta",
    "url": "https://overwatch-api.net/api/v1/hero/22",
    "alignImage": "top",
    "role": "Support",
  },
  {
    "id": 23,
    "name": "Sombra",
    "url": "https://overwatch-api.net/api/v1/hero/23",
    "alignImage": "top",
    "role": "Offense",
  },
  {
    "id": 24,
    "name": "Orisa",
    "url": "https://overwatch-api.net/api/v1/hero/24",
    "alignImage": "top",
    "role": "Tank",
  },
  {
    "id": 25,
    "name": "Doomfist",
    "url": "https://overwatch-api.net/api/v1/hero/25",
    "alignImage": "top",
    "role": "Offense",
]
